//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GF.UCenter.Common.Portable {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UCResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UCResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GF.UCenter.Common.Portable.UCResource", typeof(UCResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account not exists or password is wrong..
        /// </summary>
        internal static string Msg_AccountLoginFailedPasswordNotMatch {
            get {
                return ResourceManager.GetString("Msg_AccountLoginFailedPasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account not exists or password is wrong..
        /// </summary>
        internal static string Msg_AccountLoginFailedTokenNotMatch {
            get {
                return ResourceManager.GetString("Msg_AccountLoginFailedTokenNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account not exists..
        /// </summary>
        internal static string Msg_AccountNotExist {
            get {
                return ResourceManager.GetString("Msg_AccountNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account already exists..
        /// </summary>
        internal static string Msg_AccountRegisterFailedAlreadyExist {
            get {
                return ResourceManager.GetString("Msg_AccountRegisterFailedAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App not exists or password is wrong..
        /// </summary>
        internal static string Msg_AppAuthFailedSecretNotMatch {
            get {
                return ResourceManager.GetString("Msg_AppAuthFailedSecretNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App not exists..
        /// </summary>
        internal static string Msg_AppNotExit {
            get {
                return ResourceManager.GetString("Msg_AppNotExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read data failed..
        /// </summary>
        internal static string Msg_AppReadAccountDataFailed {
            get {
                return ResourceManager.GetString("Msg_AppReadAccountDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write data failed..
        /// </summary>
        internal static string Msg_AppWriteAccountDataFailed {
            get {
                return ResourceManager.GetString("Msg_AppWriteAccountDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal database error..
        /// </summary>
        internal static string Msg_CouchBaseError {
            get {
                return ResourceManager.GetString("Msg_CouchBaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request execution failed..
        /// </summary>
        internal static string Msg_Failed {
            get {
                return ResourceManager.GetString("Msg_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error..
        /// </summary>
        internal static string Msg_General {
            get {
                return ResourceManager.GetString("Msg_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client error..
        /// </summary>
        internal static string Msg_HttpClientError {
            get {
                return ResourceManager.GetString("Msg_HttpClientError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment create failed..
        /// </summary>
        internal static string Msg_PaymentCreateChargeFailed {
            get {
                return ResourceManager.GetString("Msg_PaymentCreateChargeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request accepted.
        /// </summary>
        internal static string Msg_Success {
            get {
                return ResourceManager.GetString("Msg_Success", resourceCulture);
            }
        }
    }
}
